sudo: false

dist: bionic

language: php

matrix:
  include:
    - php: 7.3
      env: AUTOLOAD=1
    - php: 7.3
      env: AUTOLOAD=0
    - php: 7.4
      env: AUTOLOAD=1
    - php: 7.4
      env: AUTOLOAD=0
    - php: 8.0
      env: AUTOLOAD=0      
    - php: 8.0
      env: AUTOLOAD=1     

cache:
  directories:
    - $HOME/.composer/cache/files

# before_install:
#   # Install various build dependencies. We use `travis_retry` because Composer
#   # will occasionally fail intermittently.
#   - travis_retry make vendor

script:
  - curl -sS https://getcomposer.org/installer | php
  - php composer.phar install --ignore-platform-reqs
  - php composer.phar test tests/*
