<?php
// Generated by listennotes/devtools/api-sdks/sync.py php. Do not edit.
declare(strict_types=1);

namespace ListenNotes\PodcastApi;

trait ApiMethods
{
    public function search(array $arrOptions = []): string
    {
        return $this->requestApi('GET', '/search',
            ['q', 'sort_by_date', 'type', 'offset', 'len_min', 'len_max', 'episode_count_min', 'episode_count_max', 'update_freq_min', 'update_freq_max', 'genre_ids', 'published_before', 'published_after', 'only_in', 'language', 'region', 'ocid', 'ncid', 'safe_mode', 'unique_podcasts', 'interviews_only', 'sponsored_only', 'page_size'], $arrOptions);
    }

    public function typeahead(array $arrOptions = []): string
    {
        return $this->requestApi('GET', '/typeahead',
            ['q', 'show_podcasts', 'show_genres', 'safe_mode'], $arrOptions);
    }

    public function searchEpisodeTitles(array $arrOptions = []): string
    {
        return $this->requestApi('GET', '/search_episode_titles',
            ['q', 'podcast_id', 'podcast_id_type'], $arrOptions);
    }

    public function spellcheck(array $arrOptions = []): string
    {
        return $this->requestApi('GET', '/spellcheck',
            ['q'], $arrOptions);
    }

    public function fetchRelatedSearches(array $arrOptions = []): string
    {
        return $this->requestApi('GET', '/related_searches',
            ['q'], $arrOptions);
    }

    public function fetchTrendingSearches(array $arrOptions = []): string
    {
        return $this->requestApi('GET', '/trending_searches',
            [], $arrOptions);
    }

    public function fetchBestPodcasts(array $arrOptions = []): string
    {
        return $this->requestApi('GET', '/best_podcasts',
            ['genre_id', 'page', 'region', 'publisher_region', 'language', 'sort', 'safe_mode'], $arrOptions);
    }

    public function fetchPodcastById(array $arrOptions = []): string
    {
        return $this->requestApi('GET', '/podcasts/{id}',
            ['next_episode_pub_date', 'sort'], $arrOptions);
    }

    public function deletePodcast(array $arrOptions = []): string
    {
        return $this->requestApi('DELETE', '/podcasts/{id}',
            ['reason'], $arrOptions);
    }

    public function fetchEpisodeById(array $arrOptions = []): string
    {
        return $this->requestApi('GET', '/episodes/{id}',
            ['show_transcript'], $arrOptions);
    }

    public function batchFetchEpisodes(array $arrOptions = []): string
    {
        return $this->requestApi('POST', '/episodes',
            [], $arrOptions);
    }

    public function batchFetchPodcasts(array $arrOptions = []): string
    {
        return $this->requestApi('POST', '/podcasts',
            [], $arrOptions);
    }

    public function fetchCuratedPodcastsListById(array $arrOptions = []): string
    {
        return $this->requestApi('GET', '/curated_podcasts/{id}',
            [], $arrOptions);
    }

    public function fetchPodcastGenres(array $arrOptions = []): string
    {
        return $this->requestApi('GET', '/genres',
            ['top_level_only'], $arrOptions);
    }

    public function fetchPodcastRegions(array $arrOptions = []): string
    {
        return $this->requestApi('GET', '/regions',
            [], $arrOptions);
    }

    public function fetchPodcastLanguages(array $arrOptions = []): string
    {
        return $this->requestApi('GET', '/languages',
            [], $arrOptions);
    }

    public function justListen(array $arrOptions = []): string
    {
        return $this->requestApi('GET', '/just_listen',
            [], $arrOptions);
    }

    public function fetchCuratedPodcastsLists(array $arrOptions = []): string
    {
        return $this->requestApi('GET', '/curated_podcasts',
            ['page'], $arrOptions);
    }

    public function fetchRecommendationsForPodcast(array $arrOptions = []): string
    {
        return $this->requestApi('GET', '/podcasts/{id}/recommendations',
            ['safe_mode'], $arrOptions);
    }

    public function fetchRecommendationsForEpisode(array $arrOptions = []): string
    {
        return $this->requestApi('GET', '/episodes/{id}/recommendations',
            ['safe_mode'], $arrOptions);
    }

    public function submitPodcast(array $arrOptions = []): string
    {
        return $this->requestApi('POST', '/podcasts/submit',
            [], $arrOptions);
    }

    public function fetchPlaylistById(array $arrOptions = []): string
    {
        return $this->requestApi('GET', '/playlists/{id}',
            ['type', 'last_timestamp_ms', 'sort'], $arrOptions);
    }

    public function fetchMyPlaylists(array $arrOptions = []): string
    {
        return $this->requestApi('GET', '/playlists',
            ['sort', 'page'], $arrOptions);
    }

    public function fetchAudienceForPodcast(array $arrOptions = []): string
    {
        return $this->requestApi('GET', '/podcasts/{id}/audience',
            [], $arrOptions);
    }

    public function fetchPodcastsByDomain(array $arrOptions = []): string
    {
        return $this->requestApi('GET', '/podcasts/domains/{domain_name}',
            ['page'], $arrOptions);
    }

    public function createPlaylist(array $arrOptions = []): string
    {
        return $this->requestApi('POST', '/playlists',
            [], $arrOptions);
    }

    public function updatePlaylist(array $arrOptions = []): string
    {
        return $this->requestApi('PUT', '/playlists/{id}',
            [], $arrOptions);
    }

    public function deletePlaylist(array $arrOptions = []): string
    {
        return $this->requestApi('DELETE', '/playlists/{id}',
            [], $arrOptions);
    }

    public function addPlaylistItem(array $arrOptions = []): string
    {
        return $this->requestApi('POST', '/playlists/{id}/items',
            [], $arrOptions);
    }

    public function deletePlaylistItem(array $arrOptions = []): string
    {
        return $this->requestApi('DELETE', '/playlists/{id}/items/{item_id}',
            [], $arrOptions);
    }

    public function updatePlaylistItemNotes(array $arrOptions = []): string
    {
        return $this->requestApi('PUT', '/playlists/{id}/items/{item_id}',
            [], $arrOptions);
    }

}
